const FILE_TYPE_MAP = {
  pdf: { icon: 'Document', color: '#E74C3C', type: 'pdf', label: 'PDF文档' },
  doc: { icon: 'Document', color: '#3498DB', type: 'document', label: 'Word文档' },
  docx: { icon: 'Document', color: '#3498DB', type: 'document', label: 'Word文档' },
  xls: { icon: 'Document', color: '#27AE60', type: 'document', label: 'Excel表格' },
  xlsx: { icon: 'Document', color: '#27AE60', type: 'document', label: 'Excel表格' },
  ppt: { icon: 'Document', color: '#D35400', type: 'ppt', label: 'PPT演示文稿' },
  pptx: { icon: 'Document', color: '#D35400', type: 'ppt', label: 'PPT演示文稿' },
  jpg: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'JPEG图像' },
  jpeg: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'JPEG图像' },
  png: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'PNG图像' },
  gif: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'GIF动图' },
  webp: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'WebP图像' },
  bmp: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'BMP图像' },
  svg: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'SVG矢量图' },
  ico: { icon: 'Picture', color: '#9B59B6', type: 'image', label: 'ICO图标' },
  mp4: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'MP4视频' },
  avi: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'AVI视频' },
  mkv: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'MKV视频' },
  mov: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'MOV视频' },
  webm: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'WebM视频' },
  wmv: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'WMV视频' },
  flv: { icon: 'VideoPlay', color: '#E91E63', type: 'video', label: 'FLV视频' },
  mp3: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'MP3音频' },
  wav: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'WAV音频' },
  flac: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'FLAC无损音频' },
  aac: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'AAC音频' },
  m4a: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'M4A音频' },
  ogg: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'OGG音频' },
  wma: { icon: 'Headset', color: '#00BCD4', type: 'audio', label: 'WMA音频' },
  zip: { icon: 'Files', color: '#FF9800', type: 'archive', label: 'ZIP压缩包' },
  rar: { icon: 'Files', color: '#FF9800', type: 'archive', label: 'RAR压缩包' },
  '7z': { icon: 'Files', color: '#FF9800', type: 'archive', label: '7Z压缩包' },
  tar: { icon: 'Files', color: '#FF9800', type: 'archive', label: 'TAR归档' },
  gz: { icon: 'Files', color: '#FF9800', type: 'archive', label: 'GZ压缩包' },
  bz2: { icon: 'Files', color: '#FF9800', type: 'archive', label: 'BZ2压缩包' },
  txt: { icon: 'Document', color: '#95A5A6', type: 'text', label: '纯文本' },
  log: { icon: 'Document', color: '#95A5A6', type: 'text', label: '日志文件' },
  md: { icon: 'Document', color: '#34495E', type: 'markdown', label: 'Markdown文档' },
  json: { icon: 'Document', color: '#F39C12', type: 'code', label: 'JSON数据' },
  xml: { icon: 'Document', color: '#F39C12', type: 'code', label: 'XML数据' },
  yaml: { icon: 'Document', color: '#F39C12', type: 'code', label: 'YAML配置' },
  yml: { icon: 'Document', color: '#F39C12', type: 'code', label: 'YAML配置' },
  js: { icon: 'Document', color: '#F39C12', type: 'code', label: 'JavaScript脚本' },
  ts: { icon: 'Document', color: '#3178C6', type: 'code', label: 'TypeScript脚本' },
  jsx: { icon: 'Document', color: '#61DAFB', type: 'code', label: 'React组件' },
  tsx: { icon: 'Document', color: '#3178C6', type: 'code', label: 'React组件' },
  vue: { icon: 'Document', color: '#42B883', type: 'code', label: 'Vue组件' },
  html: { icon: 'Document', color: '#E34F26', type: 'code', label: 'HTML网页' },
  htm: { icon: 'Document', color: '#E34F26', type: 'code', label: 'HTML网页' },
  css: { icon: 'Document', color: '#1572B6', type: 'code', label: 'CSS样式表' },
  scss: { icon: 'Document', color: '#CC6699', type: 'code', label: 'SCSS样式表' },
  sass: { icon: 'Document', color: '#CC6699', type: 'code', label: 'SASS样式表' },
  less: { icon: 'Document', color: '#1D365D', type: 'code', label: 'LESS样式表' },
  py: { icon: 'Document', color: '#3776AB', type: 'code', label: 'Python脚本' },
  java: { icon: 'Document', color: '#ED8B00', type: 'code', label: 'Java源码' },
  c: { icon: 'Document', color: '#A8B9CC', type: 'code', label: 'C源码' },
  cpp: { icon: 'Document', color: '#00599C', type: 'code', label: 'C++源码' },
  h: { icon: 'Document', color: '#A8B9CC', type: 'code', label: 'C头文件' },
  go: { icon: 'Document', color: '#00ADD8', type: 'code', label: 'Go源码' },
  rs: { icon: 'Document', color: '#DEA584', type: 'code', label: 'Rust源码' },
  php: { icon: 'Document', color: '#777BB4', type: 'code', label: 'PHP脚本' },
  rb: { icon: 'Document', color: '#CC342D', type: 'code', label: 'Ruby脚本' },
  swift: { icon: 'Document', color: '#FA7343', type: 'code', label: 'Swift源码' },
  kt: { icon: 'Document', color: '#7F52FF', type: 'code', label: 'Kotlin源码' },
  sh: { icon: 'Document', color: '#4EAA25', type: 'code', label: 'Shell脚本' },
  bash: { icon: 'Document', color: '#4EAA25', type: 'code', label: 'Bash脚本' },
  bat: { icon: 'Document', color: '#C1F12E', type: 'code', label: '批处理脚本' },
  sql: { icon: 'Document', color: '#336791', type: 'code', label: 'SQL脚本' },
  epub: { icon: 'Document', color: '#8E44AD', type: 'ebook', label: 'EPUB电子书' },
  mobi: { icon: 'Document', color: '#8E44AD', type: 'ebook', label: 'MOBI电子书' },
  azw3: { icon: 'Document', color: '#8E44AD', type: 'ebook', label: 'AZW3电子书' },
  csv: { icon: 'Document', color: '#27AE60', type: 'text', label: 'CSV表格' },
  rtf: { icon: 'Document', color: '#3498DB', type: 'document', label: 'RTF文档' },
  torrent: { icon: 'Document', color: '#8E44AD', type: 'other', label: 'BT种子' },
  iso: { icon: 'Files', color: '#95A5A6', type: 'archive', label: 'ISO镜像' },
  dmg: { icon: 'Files', color: '#95A5A6', type: 'archive', label: 'DMG镜像' },
  exe: { icon: 'Document', color: '#95A5A6', type: 'other', label: 'Windows程序' },
  app: { icon: 'Document', color: '#95A5A6', type: 'other', label: 'macOS程序' },
  apk: { icon: 'Document', color: '#3DDC84', type: 'other', label: 'Android应用' },
  ipa: { icon: 'Document', color: '#007AFF', type: 'other', label: 'iOS应用' }
}

export function getFileTypeInfo(filename) {
  if (!filename) return { icon: 'Document', color: '#95A5A6', type: 'other', label: '文件' }
  
  const ext = filename.split('.').pop()?.toLowerCase()
  return FILE_TYPE_MAP[ext] || { icon: 'Document', color: '#95A5A6', type: 'other', label: '文件' }
}

export function formatFileSize(bytes) {
  if (!bytes) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}